name = "statpedia-player-props"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Enable workers.dev for subdomain registration
workers_dev = true

# Cron triggers for automatic multi-league ingestion
[triggers]
crons = ["*/10 * * * *"]  # Every 10 minutes for all leagues

# Global configuration (will be inherited by all environments)
[vars]
SPORTSODDS_API_KEY = "f05c244cbea5222d806f91c412350940"
SGO_API_KEY = "f05c244cbea5222d806f91c412350940"
SPORTSGAMEODDS_API_KEY = "f05c244cbea5222d806f91c412350940"
SUPABASE_URL = "https://rfdrifnsfobqlzorcesn.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZHJpZm5zZm9icWx6b3JjZXNuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTA0ODgzNiwiZXhwIjoyMDc0NjI0ODM2fQ.E9LQFvqVs9Z1cXoS34ov5qV3jBkbqCHPCL16GBt480g"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZHJpZm5zZm9icWx6b3JjZXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDg4MzYsImV4cCI6MjA3NDYyNDgzNn0.oUzP1pTapCMEaaPXzia2uqn-m3L9BRR82_RYcUXqykI"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
NEON_DATABASE_URL = "postgresql://neondb_owner:npg_vdkFqWJVi42j@ep-broad-waterfall-a8uchv9a-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"

[env.production]
name = "statpedia-player-props"

# Production environment variables
[env.production.vars]
SPORTSODDS_API_KEY = "f05c244cbea5222d806f91c412350940"
SGO_API_KEY = "f05c244cbea5222d806f91c412350940"
CACHE_TTL_SECONDS = "300"
MAX_EVENTS_PER_REQUEST = "100"
MAX_PROPS_PER_REQUEST = "500"
SUPABASE_URL = "https://rfdrifnsfobqlzorcesn.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZHJpZm5zZm9icWx6b3JjZXNuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTA0ODgzNiwiZXhwIjoyMDc0NjI0ODM2fQ.E9LQFvqVs9Z1cXoS34ov5qV3jBkbqCHPCL16GBt480g"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
NEON_DATABASE_URL = "postgresql://neondb_owner:npg_vdkFqWJVi42j@ep-broad-waterfall-a8uchv9a-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"

# Production R2 bucket
[[env.production.r2_buckets]]
binding = "PLAYER_PROPS_CACHE"
bucket_name = "statpedia-player-props-cache"

# Production KV namespace
[[env.production.kv_namespaces]]
binding = "API_ANALYTICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Production KV namespace for cache locks
[[env.production.kv_namespaces]]
binding = "CACHE_LOCKS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Production KV namespace for metrics
[[env.production.kv_namespaces]]
binding = "METRICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

[env.staging]
name = "statpedia-player-props-staging"

# Staging environment variables
[env.staging.vars]
SPORTSODDS_API_KEY = "f05c244cbea5222d806f91c412350940"
SGO_API_KEY = "f05c244cbea5222d806f91c412350940"
CACHE_TTL_SECONDS = "300"
MAX_EVENTS_PER_REQUEST = "100"
MAX_PROPS_PER_REQUEST = "500"
SUPABASE_URL = "https://rfdrifnsfobqlzorcesn.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZHJpZm5zZm9icWx6b3JjZXNuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTA0ODgzNiwiZXhwIjoyMDc0NjI0ODM2fQ.E9LQFvqVs9Z1cXoS34ov5qV3jBkbqCHPCL16GBt480g"
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"
NEON_DATABASE_URL = "postgresql://neondb_owner:npg_vdkFqWJVi42j@ep-broad-waterfall-a8uchv9a-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"

# Staging R2 bucket
[[env.staging.r2_buckets]]
binding = "PLAYER_PROPS_CACHE"
bucket_name = "statpedia-player-props-cache"

# Staging KV namespace
[[env.staging.kv_namespaces]]
binding = "API_ANALYTICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Staging KV namespace for cache locks
[[env.staging.kv_namespaces]]
binding = "CACHE_LOCKS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Staging KV namespace for metrics
[[env.staging.kv_namespaces]]
binding = "METRICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"