name = "statpedia-player-props"
main = "src/worker.ts"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

# Enable workers.dev for subdomain registration
workers_dev = true

# Cron triggers for automatic multi-league ingestion (optional)
[triggers]
crons = ["*/10 * * * *"]

# Global configuration (keep secrets out of source; set via `wrangler secret put`)
[vars]
# Cache TTL (seconds) for GET /api/player-props when not force_refresh
CACHE_TTL_SECONDS = "300"
# Max items to request per SGO call (will be bounded per sport)
MAX_EVENTS_PER_REQUEST = "100"
MAX_PROPS_PER_REQUEST = "500"
# SGO API key must be set as a secret at deploy time:
#   wrangler secret put SGO_API_KEY


[env.production]
name = "statpedia-player-props"

# Production environment variables
[env.production.vars]
CACHE_TTL_SECONDS = "300"
MAX_EVENTS_PER_REQUEST = "100"
MAX_PROPS_PER_REQUEST = "500"

# Production R2 bucket
[[env.production.r2_buckets]]
binding = "PLAYER_PROPS_CACHE"
bucket_name = "statpedia-player-props-cache"

# Production KV namespace
[[env.production.kv_namespaces]]
binding = "API_ANALYTICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Production KV namespace for cache locks
[[env.production.kv_namespaces]]
binding = "CACHE_LOCKS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Production KV namespace for metrics
[[env.production.kv_namespaces]]
binding = "METRICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

[env.staging]
name = "statpedia-player-props-staging"

# Staging environment variables
[env.staging.vars]
CACHE_TTL_SECONDS = "300"
MAX_EVENTS_PER_REQUEST = "100"
MAX_PROPS_PER_REQUEST = "500"

# Staging R2 bucket
[[env.staging.r2_buckets]]
binding = "PLAYER_PROPS_CACHE"
bucket_name = "statpedia-player-props-cache"

# Staging KV namespace
[[env.staging.kv_namespaces]]
binding = "API_ANALYTICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Staging KV namespace for cache locks
[[env.staging.kv_namespaces]]
binding = "CACHE_LOCKS"
id = "8506dfcc9c964d20946e1b7ef872db7b"

# Staging KV namespace for metrics
[[env.staging.kv_namespaces]]
binding = "METRICS"
id = "8506dfcc9c964d20946e1b7ef872db7b"