name = "statpedia-auth"
main = "auth-worker.js"
compatibility_date = "2024-01-15"

# Environment variables
[vars]
JWT_SECRET = "statpedia-super-secret-jwt-key-2024"
HASURA_GRAPHQL_ENDPOINT = "https://graphql-engine-latest-statpedia.onrender.com"

# R2 bucket binding
[[r2_buckets]]
binding = "PLAYER_IMAGES"
bucket_name = "statpedia-player-images"

# KV binding for caching
[[kv_namespaces]]
binding = "CACHE"
id = "ef9b84968b61460dbd8697512572e8e2"
