// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfdlqjktmyoyexguzwjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZGxxamt0bXlveWV4Z3V6d2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MDU4MDcsImV4cCI6MjA5NDE4MTgwN30.BG-UeYyfp_SInzepQmpuI35IXIq6IuLC_VfsAnfdgAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});