// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayllbtbhiopkuvogyakb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bGxidGJoaW9wa3V2b2d5YWtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTQ4ODAsImV4cCI6MjA3NDY3MDg4MH0.OXMJiSiyG6ju_PirMsY5ovZOsFqTg6OCsp_-TDDlq5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});